#!/usr/bin/env bash
# Regenerates the vendored MIRACL Core sources under icrc167-canister-sig/src/miracl/java.
#
# The upstream project is not published to Maven Central as a BLS12-381 artifact: its Java
# build is a generator. config64.py copies templates and substitutes the curve, so the only
# honest way to say where these files came from is to run it. This script does that and
# nothing else, so the answer to "is this really upstream?" is "run it again and diff".
#
# Only the classes the verifier needs are kept. Two omissions are deliberate:
#
#   * BLS.java. Its bls_hash_to_point hard-codes the domain separation tag
#     BLS_SIG_BLS12381G1_XMD:SHA-256_SVDW_RO_NUL_, and the IC specifies ..._SSWU_RO_NUL_.
#     Anything that called it would compute a different point and reject every genuine
#     signature, so it is not shipped; MiraclBls.kt carries the routine with the right tag.
#   * ECDH/EDDSA/HPKE/MPIN and the post-quantum schemes, which nothing here uses.
#
# Usage: scripts/vendor-miracl.sh [commit-ish]
set -euo pipefail

UPSTREAM_URL="https://github.com/miracl/core.git"
UPSTREAM_REF="${1:-master}"
CURVE_MENU_ENTRY=31 # "BLS12381" in config64.py's list; the script prints the menu it used.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
target="$repo_root/icrc167-canister-sig/src/miracl/java"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

git clone --quiet "$UPSTREAM_URL" "$work/core"
git -C "$work/core" checkout --quiet "$UPSTREAM_REF"
sha="$(git -C "$work/core" rev-parse HEAD)"

cd "$work/core/java"
printf '%s\n0\n' "$CURVE_MENU_ENTRY" | python3 config64.py > "$work/config.log"
grep -q "^${CURVE_MENU_ENTRY}\. BLS12381$" "$work/config.log" \
  || { echo "menu entry $CURVE_MENU_ENTRY is no longer BLS12381; check config64.py" >&2; exit 1; }

generated="$work/core/java/core/src/main/java/org/miracl/core"

rm -rf "$target"
mkdir -p "$target/org/miracl/core/BLS12381"

# The pairing arithmetic, the curve, and the field.
for f in BIG DBIG CONFIG_BIG CONFIG_CURVE CONFIG_FIELD ECP ECP2 FP FP2 FP4 FP12 PAIR ROM; do
  cp "$generated/BLS12381/$f.java" "$target/org/miracl/core/BLS12381/$f.java"
done
# Shared classes those pull in: HMAC for expand_message_xmd, the hashes it dispatches to,
# and RAND, which appears in signatures of methods this code never calls.
for f in HMAC HASH256 HASH384 HASH512 SHA3 RAND; do
  cp "$generated/$f.java" "$target/org/miracl/core/$f.java"
done

cp "$work/core/LICENSE.txt" "$target/LICENSE.txt"

cat > "$target/PROVENANCE" <<EOF
Generated by scripts/vendor-miracl.sh — do not edit these files by hand.

source:   $UPSTREAM_URL
commit:   $sha
command:  java/config64.py, menu entry $CURVE_MENU_ENTRY (BLS12381)
license:  Apache-2.0, see LICENSE.txt in this directory

BLS.java is deliberately not included: its domain separation tag is
BLS_SIG_BLS12381G1_XMD:SHA-256_SVDW_RO_NUL_ and the Internet Computer specifies
BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_NUL_.
EOF

echo "vendored miracl/core@$sha into ${target#"$repo_root"/}"
find "$target" -name '*.java' | wc -l | xargs echo "java files:"
